<?php

declare(strict_types=1);

if (! function_exists('ui_supported_locales')) {
    /**
     * @return list<string>
     */
    function ui_supported_locales(): array
    {
        return ['it', 'en'];
    }
}

if (! function_exists('ui_locale')) {
    function ui_locale(): string
    {
        $locale = service('request')->getLocale();

        return in_array($locale, ui_supported_locales(), true) ? $locale : 'en';
    }
}

if (! function_exists('ui_text')) {
    /**
     * @param array<string, string|int|float> $replace
     */
    function ui_text(string $key, array $replace = [], ?string $locale = null): string
    {
        $resolvedLocale = $locale;

        if ($resolvedLocale === null || ! in_array($resolvedLocale, ui_supported_locales(), true)) {
            $resolvedLocale = ui_locale();
        }

        $catalog = [
            'en' => [
                'theme' => 'Theme',
                'theme.system' => 'System',
                'theme.light' => 'Light',
                'theme.dark' => 'Dark',
                'profile.title' => 'User profile',
                'profile.lead' => 'Manage identity, interface language, theme, timezone and email preferences.',
                'profile.identity' => 'Identity',
                'profile.identity.help' => 'Visible name and basic profile details.',
                'profile.preferences' => 'Preferences',
                'profile.preferences.help' => 'Language, theme and timezone applied across the interface.',
                'profile.avatar' => 'Avatar path or URL',
                'profile.locale' => 'Language',
                'profile.locale.it' => 'Italian',
                'profile.locale.en' => 'English',
                'profile.theme' => 'Theme',
                'profile.timezone' => 'Timezone',
                'profile.email_notifications' => 'Enable email notifications',
                'profile.save' => 'Save profile',
                'profile.verify_email' => 'Verify email',
                'profile.locale.help' => 'Language changes are applied across the interface on the next request.',
                'profile.updated' => 'Profile updated.',
                'profile.delete.title' => 'Close account',
                'profile.delete.lead' => 'Remove personal access and anonymize profile data while preserving shared household history required for ongoing balances and audits.',
                'profile.delete.help' => 'This action signs you out, revokes active tokens, removes direct profile data and anonymizes your identity inside existing shared records.',
                'profile.delete.password' => 'Current password',
                'profile.delete.confirm' => 'Type DELETE to confirm',
                'profile.delete.confirm.help' => 'Your account will be closed immediately after confirmation.',
                'profile.delete.submit' => 'Delete my account',
                'profile.delete.completed' => 'Account closed and personal profile data removed.',
                'profile.delete.password_invalid' => 'Current password is not valid.',
                'profile.delete.confirm_invalid' => 'Type DELETE to confirm account removal.',
                'profile.delete.unavailable' => 'Account is not available anymore.',
                'profile.delete.anonymized_name' => 'Deleted user #{id}',
                'expense.step.details' => 'Details',
                'expense.step.payers' => 'Payers',
                'expense.step.splits' => 'Participants & split',
                'expense.step.review' => 'Review',
                'expense.step.next' => 'Next step',
                'expense.step.back' => 'Back',
                'expense.step.submit.create' => 'Create expense',
                'expense.step.submit.update' => 'Save changes',
                'expense.label.currency' => 'Currency',
                'expense.label.category' => 'Category',
                'expense.label.split_method' => 'Split method',
                'expense.label.receipt' => 'Receipt or attachment',
                'expense.label.receipt.current' => 'Current receipt: {name}',
                'expense.label.uncategorized' => 'Uncategorized',
                'expense.auto.equal' => 'Auto split equally',
                'expense.auto.remainder' => 'Remainder assigned automatically',
                'expense.auto.percentages' => 'Percentages normalized to 100%',
                'expense.auto.shares' => 'Shares converted automatically',
                'expense.method.equal' => 'Equal split',
                'expense.method.exact' => 'Exact amounts',
                'expense.method.percentage' => 'Percentage split',
                'expense.method.shares' => 'Shares split',
                'expense.preview.owes' => 'Owes {amount}',
                'expense.preview.pays' => 'Pays {amount}',
                'expense.error.total_positive' => 'Expense total must be greater than zero.',
                'expense.error.category_invalid' => 'The selected category is not available for this household.',
                'expense.error.split_method_invalid' => 'Unsupported split method.',
                'expense.error.member_payer_invalid' => 'One selected payer does not belong to this household.',
                'expense.error.member_participant_invalid' => 'One selected participant does not belong to this household.',
                'expense.error.payer_positive' => 'Each payer must have an amount greater than zero.',
                'expense.error.payers_required' => 'Select at least one payer.',
                'expense.error.payers_total' => 'The payer total must match the expense total.',
                'expense.error.participants_required' => 'Select at least one participant.',
                'expense.error.money_numeric' => 'Monetary amounts must be numeric.',
                'expense.error.numeric_invalid' => 'Invalid numeric value.',
                'expense.error.percentage_positive' => 'Each percentage must be greater than zero.',
                'expense.error.share_positive' => 'Each share value must be greater than zero.',
                'expense.error.exact_total' => 'For exact split, owed amounts must add up to the expense total.',
                'expense.error.percentage_total' => 'For percentage split, percentages must add up to 100.',
                'expense.error.shares_total' => 'For shares split, total shares must be greater than zero.',
                'expense.error.distribution_invalid' => 'The selected distribution does not produce valid shares.',
                'common.none' => 'None',
                'common.all' => 'All',
                'common.open' => 'Open',
                'common.close' => 'Close',
                'common.details' => 'Details',
                'common.save' => 'Save',
                'common.cancel' => 'Cancel',
                'common.reset' => 'Reset',
                'common.filter' => 'Filter',
                'common.search' => 'Search',
                'common.unread' => 'Unread',
                'common.scope.account' => 'Account',
                'common.scope.household_global' => 'Household + global',
                'shell.menu' => 'Menu',
                'shell.active_household' => 'Active household',
                'shell.workspace_tools' => 'Workspace tools',
                'shell.theme' => 'Theme',
                'shell.household' => 'Household',
                'shell.notifications' => 'Notifications',
                'shell.profile' => 'Profile',
                'shell.guest' => 'Guest',
                'shell.login_to_switch' => 'Log in to switch household.',
                'shell.no_household_available' => 'No household available.',
                'shell.log_in' => 'Log in',
                'shell.create_account' => 'Create account',
                'shell.logout' => 'Logout',
                'shell.household_dashboard' => 'Household dashboard',
                'nav.dashboard' => 'Dashboard',
                'nav.expenses' => 'Expenses',
                'nav.balances' => 'Balances',
                'nav.chores' => 'Chores',
                'nav.shopping' => 'Shopping',
                'nav.pinboard' => 'Pinboard',
                'nav.notifications' => 'Notifications',
                'nav.reports' => 'Reports',
                'nav.settlements' => 'Settlements',
                'nav.members' => 'Members',
                'nav.invitations' => 'Invitations',
                'nav.roles' => 'Roles',
                'nav.recurring' => 'Recurring',
                'nav.settings' => 'Settings',
                'notification.center.title' => 'Notification center',
                'notification.center.lead' => 'Unified feed for invitations, expenses, settlements, chores and board updates.',
                'notification.mark_all' => 'Mark all as read',
                'notification.mark_read' => 'Mark as read',
                'notification.open_center' => 'Open notification center',
                'notification.live_enabled' => 'Live updates enabled',
                'notification.empty.title' => 'No unread notifications',
                'notification.empty.message' => 'New invitations, expenses, chores and comments will appear here.',
                'notification.unread_only' => 'Unread only',
                'notification.show_history' => 'Show read history',
                'notification.badge.new' => 'New',
                'notification.type.invitation_received' => 'Invitation',
                'notification.type.expense_created' => 'New expense',
                'notification.type.expense_updated' => 'Expense updated',
                'notification.type.settlement_created' => 'Settlement',
                'notification.type.chore_assigned' => 'Chore assigned',
                'notification.type.chore_due_soon' => 'Chore reminder',
                'notification.type.chore_completed' => 'Chore completed',
                'notification.type.pinboard_post_created' => 'New post',
                'notification.type.pinboard_comment_created' => 'Pinboard comment',
                'notification.title.invitation_received' => 'Invitation received',
                'notification.body.invitation_received' => 'You were invited to join {household} as {role}.',
                'notification.title.expense_created' => 'New expense logged',
                'notification.title.expense_updated' => 'Expense updated',
                'notification.title.settlement_created' => 'Settlement recorded',
                'notification.title.chore_assigned' => 'New chore assigned',
                'notification.body.chore_assigned' => '{title} due by {due_at}.',
                'notification.title.chore_due_soon' => 'Chore due soon',
                'notification.body.chore_due_soon' => '{title} is due by {due_at}.',
                'notification.title.chore_completed' => 'Chore completed',
                'notification.body.chore_completed' => '{member} completed {title}.',
                'notification.title.pinboard_post_created' => 'New pinboard post',
                'notification.title.pinboard_comment_created' => 'New pinboard comment',
                'dashboard.title' => 'Household dashboard',
                'dashboard.lead.default' => 'Operational overview of expenses, chores, shopping and communication for the active tenant.',
                'dashboard.badge.debt_simplification' => 'Debt simplification enabled',
                'dashboard.metric.personal_balance' => 'Personal balance',
                'dashboard.metric.open_transfers' => 'Open transfers',
                'dashboard.metric.open_chores' => 'Open chores',
                'dashboard.metric.urgent_items' => 'Urgent shopping',
                'dashboard.metric.unread_notifications' => 'Unread notifications',
                'dashboard.metric.active_members' => 'Active members',
                'dashboard.section.my_balances' => 'My balances',
                'dashboard.section.transfer_summary' => 'Transfer summary',
                'dashboard.section.latest_expenses' => 'Latest expenses',
                'dashboard.section.upcoming_chores' => 'Upcoming chores',
                'dashboard.section.shopping' => 'Urgent and open items',
                'dashboard.section.pinboard' => 'Latest posts',
                'dashboard.section.notifications' => 'Recent feed',
                'dashboard.section.quick_actions' => 'Active workflows',
                'dashboard.note.simplified' => 'Simplified suggestions derived from net balances. The real ledger remains unchanged.',
                'dashboard.note.real' => 'Real balance derived from recorded expenses and settlements.',
                'dashboard.empty.balance.title' => 'No balance available',
                'dashboard.empty.balance.message' => 'Future expenses and settlements will populate this section.',
                'dashboard.empty.transfer.title' => 'No open transfers',
                'dashboard.empty.transfer.message' => 'Balances are already settled.',
                'dashboard.empty.expenses.title' => 'No recent expenses',
                'dashboard.empty.expenses.message' => 'Create the first expense to populate the household feed.',
                'dashboard.empty.chores.title' => 'No upcoming chores',
                'dashboard.empty.chores.message' => 'Upcoming occurrences will appear here as soon as they are generated.',
                'dashboard.empty.shopping.title' => 'No urgent items',
                'dashboard.empty.shopping.message' => 'Shopping lists are under control.',
                'dashboard.empty.posts.title' => 'No recent posts',
                'dashboard.empty.posts.message' => 'Use the pinboard for notes, announcements and shared reminders.',
                'dashboard.empty.notifications.title' => 'No recent notifications',
                'dashboard.empty.notifications.message' => 'Invitations, expenses, chores and comments will appear here.',
                'settings.title' => 'Household settings',
                'settings.lead' => 'Base tenant configuration, active modules and custom expense groups.',
                'settings.expense_groups' => 'Expense groups',
                'settings.expense_groups.help' => 'System groups are translated automatically. Custom groups are specific to this household.',
                'settings.expense_groups.empty' => 'No custom groups yet.',
                'settings.expense_groups.system' => 'System group',
                'settings.expense_groups.custom' => 'Custom group',
                'settings.expense_groups.create' => 'Create group',
                'settings.expense_groups.update' => 'Save group',
                'settings.expense_groups.delete' => 'Delete',
                'settings.expense_groups.name' => 'Group name',
                'settings.expense_groups.description' => 'Description',
                'settings.expense_groups.color' => 'Color',
                'settings.expense_groups.members' => 'Members',
                'settings.expense_groups.members_help' => 'Only selected members can share expenses and settlements inside this group.',
                'settings.expense_groups.created' => 'Expense group created.',
                'settings.expense_groups.updated' => 'Expense group updated.',
                'settings.expense_groups.deleted' => 'Expense group deleted.',
                'settings.expense_groups.name_required' => 'Enter a group name.',
                'settings.expense_groups.members_required' => 'Select at least one member for this expense group.',
                'settings.expense_groups.not_found' => 'Expense group not available.',
                'settings.expense_groups.system_locked' => 'System groups cannot be edited here.',
                'expense.label.group' => 'Expense group',
                'expense.label.group.general' => 'General',
                'expense.error.group_invalid' => 'The selected expense group is not available for this household.',
                'settlement.label.group' => 'Expense group',
                'report.balance.by_member_group' => 'By expense group for this member',
                'report.expenses.title' => 'Expense reports',
                'report.expenses.lead' => 'Breakdown by category, month and member without implicit FX conversion.',
                'report.expenses.by_category' => 'By category',
                'report.expenses.by_month' => 'Monthly trend',
                'report.expenses.by_user' => 'By member',
                'report.expenses.top_spenders' => 'Top spenders',
                'report.expenses.recent' => 'Recent expenses',
                'report.expenses.chart.monthly' => 'Monthly expense trend',
                'report.expenses.chart.categories' => 'Monthly totals by expense group',
                'report.balance.by_group' => 'By expense group',
                'report.balance.group_unassigned' => 'No expense group',
                'report.balance.overall' => 'Overall total',
                'report.balance.gets_back' => 'To receive',
                'report.balance.owes' => 'To pay',
                'category.uncategorized' => 'Uncategorized',
                'category.groceries' => 'Groceries',
                'category.utilities' => 'Utilities',
                'category.rent' => 'Rent',
                'category.internet' => 'Internet',
                'category.cleaning' => 'Cleaning',
                'category.transport' => 'Transport',
                'category.entertainment' => 'Entertainment',
                'category.misc' => 'Miscellaneous',
                'gdpr.link.privacy' => 'Informativa privacy',
                'gdpr.link.cookies' => 'Informativa cookie',
                'gdpr.link.manage' => 'Cookie preferences',
                'gdpr.flash.saved' => 'Cookie preferences updated.',
                'gdpr.banner.title' => 'Privacy and cookie choices',
                'gdpr.banner.body' => 'We use essential cookies to keep sign-in, security and household features working. Preference, analytics and marketing storage remain disabled until you choose otherwise.',
                'gdpr.banner.essential' => 'Essential only',
                'gdpr.banner.manage' => 'Manage choices',
                'gdpr.banner.accept_all' => 'Accept all',
                'gdpr.modal.title' => 'Cookie preferences',
                'gdpr.modal.body' => 'Choose which optional technologies can be enabled on this device. Essential cookies stay active because they are required for security and core product functionality.',
                'gdpr.category.necessary' => 'Strictly necessary',
                'gdpr.category.preferences' => 'Preferences',
                'gdpr.category.analytics' => 'Analitiche',
                'gdpr.category.marketing' => 'Marketing',
                'gdpr.category.enable' => 'Enable category',
                'gdpr.category.always_on' => 'Always active',
                'gdpr.category.necessary.help' => 'Required for authentication, CSRF protection, session continuity and consent storage.',
                'gdpr.category.preferences.help' => 'Stores optional interface preferences such as remembered theme selection on shared/public devices.',
                'gdpr.category.analytics.help' => 'Reserved for privacy-friendly measurement tools. No optional analytics are enabled by default.',
                'gdpr.category.marketing.help' => 'Reserved for advertising or retargeting technologies. These are disabled by default.',
                'gdpr.modal.save' => 'Save choices',
                'gdpr.policy.version' => 'Policy version: {version}',
                'gdpr.privacy.title' => 'Informativa privacy',
                'gdpr.privacy.lead' => 'FamilyJam processes account, household and activity data to provide shared budgeting, chores, shopping and collaboration features for the active household.',
                'gdpr.privacy.processing.title' => 'Processing scope',
                'gdpr.privacy.processing.body' => 'User accounts, household memberships, expenses, chores, shopping lists, notifications and audit events required to operate the service.',
                'gdpr.privacy.cookies.title' => 'Cookies and local storage',
                'gdpr.privacy.cookies.body' => 'Essential cookies are used for security and login state. Optional preference storage is disabled until consent is recorded.',
                'gdpr.privacy.bases.title' => 'Legal bases',
                'gdpr.privacy.bases.contract' => 'Contract/performance of the service for account access, household participation and collaborative features.',
                'gdpr.privacy.bases.legitimate' => 'Legitimate interest for security, abuse prevention, logging and operational resilience.',
                'gdpr.privacy.bases.consent' => 'Consent for optional preference, analytics or marketing technologies when they are introduced.',
                'gdpr.privacy.rights.title' => 'Data subject rights',
                'gdpr.privacy.rights.body' => 'Users can request access, correction or deletion of personal data according to the applicable GDPR framework and local law.',
                'gdpr.privacy.rights.access' => 'Access and obtain a copy of personal data.',
                'gdpr.privacy.rights.rectification' => 'Correct inaccurate or incomplete information.',
                'gdpr.privacy.rights.erasure' => 'Request deletion when retention is no longer justified.',
                'gdpr.privacy.rights.portability' => 'Request portable structured data where applicable.',
                'gdpr.privacy.rights.objection' => 'Object to optional processing that relies on consent or legitimate interest.',
                'gdpr.privacy.retention.title' => 'Retention',
                'gdpr.privacy.retention.body' => 'Operational data is retained only as long as needed for household collaboration, legal obligations, dispute resolution and service security. Optional consent records are versioned and retained to document the user choice history.',
                'gdpr.cookies.title' => 'Informativa cookie',
                'gdpr.cookies.lead' => 'FamilyJam defaults to essential cookies only. Optional preference, analytics and marketing storage stays disabled until the visitor records an explicit choice.',
                'gdpr.cookies.table.name' => 'Name',
                'gdpr.cookies.table.category' => 'Category',
                'gdpr.cookies.table.purpose' => 'Purpose',
                'gdpr.cookies.table.duration' => 'Duration',
                'gdpr.cookies.row.session' => 'Maintains authenticated session state and core application continuity.',
                'gdpr.cookies.row.consent_id' => 'Stores an anonymous consent identifier used to link the current browser choice to the consent log.',
                'gdpr.cookies.row.consent_state' => 'Stores the active cookie preference categories and current policy version for this browser.',
                'gdpr.cookies.row.theme' => 'Stores the remembered theme only after preference consent or when a signed-in user explicitly uses a saved interface preference.',
                'gdpr.cookies.duration.session' => 'Session / browser lifecycle',
                'gdpr.cookies.duration.six_months' => '180 days',
                'gdpr.cookies.duration.browser_local' => 'Browser local storage until cleared or updated',
                'gdpr.cookies.categories.title' => 'Categories',
                ],
            'it' => [
                'theme' => 'Tema',
                'theme.system' => 'Sistema',
                'theme.light' => 'Chiaro',
                'theme.dark' => 'Scuro',
                'profile.title' => 'Profilo utente',
                'profile.lead' => 'Gestisci identita, lingua dell\'interfaccia, tema, fuso orario e preferenze email.',
                'profile.identity' => 'Identita',
                'profile.identity.help' => 'Nome visibile e dettagli base del profilo.',
                'profile.preferences' => 'Preferenze',
                'profile.preferences.help' => 'Lingua, tema e timezone applicati in tutta l\'interfaccia.',
                'profile.avatar' => 'Percorso o URL avatar',
                'profile.locale' => 'Lingua',
                'profile.locale.it' => 'Italiano',
                'profile.locale.en' => 'Inglese',
                'profile.theme' => 'Tema',
                'profile.timezone' => 'Fuso orario',
                'profile.email_notifications' => 'Abilita notifiche email',
                'profile.save' => 'Salva profilo',
                'profile.verify_email' => 'Verifica email',
                'profile.locale.help' => 'La lingua viene applicata all\'interfaccia dalla richiesta successiva.',
                'profile.updated' => 'Profilo aggiornato.',
                'profile.delete.title' => 'Chiudi account',
                'profile.delete.lead' => 'Rimuove l\'accesso personale e anonimizza i dati profilo mantenendo la storia condivisa della household necessaria a saldi e audit.',
                'profile.delete.help' => 'L\'azione effettua logout, revoca i token attivi, rimuove i dati profilo diretti e anonimizza la tua identita nei record condivisi esistenti.',
                'profile.delete.password' => 'Password attuale',
                'profile.delete.confirm' => 'Digita DELETE per confermare',
                'profile.delete.confirm.help' => 'Dopo la conferma l\'account viene chiuso immediatamente.',
                'profile.delete.submit' => 'Elimina il mio account',
                'profile.delete.completed' => 'Account chiuso e dati profilo personali rimossi.',
                'profile.delete.password_invalid' => 'La password attuale non e valida.',
                'profile.delete.confirm_invalid' => 'Digita DELETE per confermare la rimozione dell\'account.',
                'profile.delete.unavailable' => 'L\'account non e piu disponibile.',
                'profile.delete.anonymized_name' => 'Utente eliminato #{id}',
                'expense.step.details' => 'Dettagli',
                'expense.step.payers' => 'Pagatori',
                'expense.step.splits' => 'Partecipanti e split',
                'expense.step.review' => 'Riepilogo',
                'expense.step.next' => 'Step successivo',
                'expense.step.back' => 'Indietro',
                'expense.step.submit.create' => 'Crea spesa',
                'expense.step.submit.update' => 'Salva modifiche',
                'expense.label.currency' => 'Valuta',
                'expense.label.category' => 'Categoria',
                'expense.label.split_method' => 'Metodo di split',
                'expense.label.receipt' => 'Ricevuta o allegato',
                'expense.label.receipt.current' => 'Ricevuta attuale: {name}',
                'expense.label.uncategorized' => 'Senza categoria',
                'expense.auto.equal' => 'Ripartizione automatica uguale',
                'expense.auto.remainder' => 'Residuo assegnato automaticamente',
                'expense.auto.percentages' => 'Percentuali normalizzate a 100%',
                'expense.auto.shares' => 'Quote convertite automaticamente',
                'expense.method.equal' => 'Ripartizione uguale',
                'expense.method.exact' => 'Importi esatti',
                'expense.method.percentage' => 'Ripartizione percentuale',
                'expense.method.shares' => 'Ripartizione per quote',
                'expense.preview.owes' => 'Deve {amount}',
                'expense.preview.pays' => 'Paga {amount}',
                'expense.error.total_positive' => 'Il totale della spesa deve essere maggiore di zero.',
                'expense.error.category_invalid' => 'La categoria selezionata non è disponibile per questa household.',
                'expense.error.split_method_invalid' => 'Metodo di split non supportato.',
                'expense.error.member_payer_invalid' => 'Uno dei pagatori selezionati non appartiene alla household.',
                'expense.error.member_participant_invalid' => 'Uno dei partecipanti selezionati non appartiene alla household.',
                'expense.error.payer_positive' => 'Ogni pagatore deve avere un importo maggiore di zero.',
                'expense.error.payers_required' => 'Seleziona almeno un pagatore.',
                'expense.error.payers_total' => 'La somma dei pagatori deve coincidere con il totale della spesa.',
                'expense.error.participants_required' => 'Seleziona almeno un partecipante.',
                'expense.error.money_numeric' => 'Gli importi monetari devono essere numerici.',
                'expense.error.numeric_invalid' => 'Valore numerico non valido.',
                'expense.error.percentage_positive' => 'Ogni percentuale deve essere maggiore di zero.',
                'expense.error.share_positive' => 'Ogni quota deve essere maggiore di zero.',
                'expense.error.exact_total' => 'Per lo split exact la somma delle quote deve coincidere con il totale.',
                'expense.error.percentage_total' => 'Per lo split percentage la somma delle percentuali deve essere 100.',
                'expense.error.shares_total' => 'Per lo split shares la somma delle quote deve essere maggiore di zero.',
                'expense.error.distribution_invalid' => 'La distribuzione selezionata non produce quote valide.',
                'common.none' => 'Nessuno',
                'common.all' => 'Tutti',
                'common.open' => 'Apri',
                'common.close' => 'Chiudi',
                'common.details' => 'Dettagli',
                'common.save' => 'Salva',
                'common.cancel' => 'Annulla',
                'common.reset' => 'Reset',
                'common.filter' => 'Filtra',
                'common.search' => 'Cerca',
                'common.unread' => 'Non lette',
                'common.scope.account' => 'Account',
                'common.scope.household_global' => 'Casa + globali',
                'shell.menu' => 'Menu',
                'shell.active_household' => 'Casa attiva',
                'shell.workspace_tools' => 'Strumenti casa',
                'shell.theme' => 'Tema',
                'shell.household' => 'Casa',
                'shell.notifications' => 'Notifiche',
                'shell.profile' => 'Profilo',
                'shell.guest' => 'Ospite',
                'shell.login_to_switch' => 'Accedi per cambiare household.',
                'shell.no_household_available' => 'Nessuna household disponibile.',
                'shell.log_in' => 'Accedi',
                'shell.create_account' => 'Crea account',
                'shell.logout' => 'Logout',
                'shell.household_dashboard' => 'Dashboard casa',
                'nav.dashboard' => 'Dashboard',
                'nav.expenses' => 'Spese',
                'nav.balances' => 'Saldi',
                'nav.chores' => 'Faccende',
                'nav.shopping' => 'Lista spesa',
                'nav.pinboard' => 'Bacheca',
                'nav.notifications' => 'Notifiche',
                'nav.reports' => 'Report',
                'nav.settlements' => 'Rimborsi',
                'nav.members' => 'Membri',
                'nav.invitations' => 'Inviti',
                'nav.roles' => 'Ruoli',
                'nav.recurring' => 'Ricorrenze',
                'nav.settings' => 'Impostazioni',
                'notification.center.title' => 'Centro notifiche',
                'notification.center.lead' => 'Feed unificato per inviti, spese, rimborsi, faccende e aggiornamenti bacheca.',
                'notification.mark_all' => 'Segna tutte come lette',
                'notification.mark_read' => 'Segna come letta',
                'notification.open_center' => 'Apri centro notifiche',
                'notification.live_enabled' => 'Aggiornamenti live attivi',
                'notification.live_updated' => 'Notifiche aggiornate',
                'notification.empty.title' => 'Nessuna notifica non letta',
                'notification.empty.message' => 'Nuovi inviti, spese, chore e commenti appariranno qui.',
                'notification.unread_only' => 'Solo non lette',
                'notification.show_history' => 'Mostra storico lette',
                'notification.badge.new' => 'Nuova',
                'notification.type.invitation_received' => 'Invito',
                'notification.type.expense_created' => 'Nuova spesa',
                'notification.type.expense_updated' => 'Spesa aggiornata',
                'notification.type.settlement_created' => 'Rimborso',
                'notification.type.chore_assigned' => 'Faccenda assegnata',
                'notification.type.chore_due_soon' => 'Promemoria faccenda',
                'notification.type.chore_completed' => 'Faccenda completata',
                'notification.type.pinboard_post_created' => 'Nuovo post',
                'notification.type.pinboard_comment_created' => 'Commento in bacheca',
                'notification.title.invitation_received' => 'Invito ricevuto',
                'notification.body.invitation_received' => 'Hai ricevuto un invito per entrare in {household} come {role}.',
                'notification.title.expense_created' => 'Nuova spesa registrata',
                'notification.title.expense_updated' => 'Spesa modificata',
                'notification.title.settlement_created' => 'Rimborso registrato',
                'notification.title.chore_assigned' => 'Nuova faccenda assegnata',
                'notification.body.chore_assigned' => '{title} con scadenza {due_at}.',
                'notification.title.chore_due_soon' => 'Faccenda in scadenza',
                'notification.body.chore_due_soon' => '{title} va completata entro {due_at}.',
                'notification.title.chore_completed' => 'Faccenda completata',
                'notification.body.chore_completed' => '{member} ha completato {title}.',
                'notification.title.pinboard_post_created' => 'Nuovo post in bacheca',
                'notification.title.pinboard_comment_created' => 'Nuovo commento in bacheca',
                'dashboard.title' => 'Dashboard casa',
                'dashboard.lead.default' => 'Panoramica operativa di spese, faccende, liste spesa e comunicazione della casa attiva.',
                'dashboard.badge.debt_simplification' => 'Semplificazione debiti attiva',
                'dashboard.metric.personal_balance' => 'Saldo personale',
                'dashboard.metric.open_transfers' => 'Trasferimenti aperti',
                'dashboard.metric.open_chores' => 'Faccende aperte',
                'dashboard.metric.urgent_items' => 'Lista spesa urgente',
                'dashboard.metric.unread_notifications' => 'Notifiche non lette',
                'dashboard.metric.active_members' => 'Membri attivi',
                'dashboard.section.my_balances' => 'I miei saldi',
                'dashboard.section.transfer_summary' => 'Riepilogo trasferimenti',
                'dashboard.section.latest_expenses' => 'Ultime spese',
                'dashboard.section.upcoming_chores' => 'Prossime faccende',
                'dashboard.section.shopping' => 'Item urgenti e aperti',
                'dashboard.section.pinboard' => 'Ultimi post',
                'dashboard.section.notifications' => 'Feed recente',
                'dashboard.section.quick_actions' => 'Flussi attivi',
                'dashboard.note.simplified' => 'Suggerimenti semplificati derivati dai saldi netti. Il ledger reale resta invariato.',
                'dashboard.note.real' => 'Saldo reale derivato da spese e settlement registrati.',
                'dashboard.empty.balance.title' => 'Nessun saldo disponibile',
                'dashboard.empty.balance.message' => 'Le prossime spese e i prossimi settlement popoleranno questa sezione.',
                'dashboard.empty.transfer.title' => 'Nessun trasferimento aperto',
                'dashboard.empty.transfer.message' => 'I saldi risultano gia in pari.',
                'dashboard.empty.expenses.title' => 'Nessuna spesa recente',
                'dashboard.empty.expenses.message' => 'Crea la prima spesa per popolare il feed household.',
                'dashboard.empty.chores.title' => 'Nessuna faccenda in arrivo',
                'dashboard.empty.chores.message' => 'Le prossime occorrenze appariranno qui appena generate.',
                'dashboard.empty.shopping.title' => 'Nessun item urgente',
                'dashboard.empty.shopping.message' => 'Le shopping list sono sotto controllo.',
                'dashboard.empty.posts.title' => 'Nessun post recente',
                'dashboard.empty.posts.message' => 'Usa la bacheca per note, annunci e promemoria condivisi.',
                'dashboard.empty.notifications.title' => 'Nessuna notifica recente',
                'dashboard.empty.notifications.message' => 'Inviti, spese, faccende e commenti appariranno qui.',
                'settings.title' => 'Impostazioni casa',
                'settings.lead' => 'Configurazione base della casa, moduli attivi e gruppi spesa personalizzati.',
                'settings.expense_groups' => 'Gruppi spesa',
                'settings.expense_groups.help' => 'I gruppi di sistema vengono tradotti automaticamente. I gruppi custom restano specifici di questa household.',
                'settings.expense_groups.empty' => 'Nessun gruppo custom ancora creato.',
                'settings.expense_groups.system' => 'Gruppo di sistema',
                'settings.expense_groups.custom' => 'Gruppo custom',
                'settings.expense_groups.create' => 'Crea gruppo',
                'settings.expense_groups.update' => 'Salva gruppo',
                'settings.expense_groups.delete' => 'Elimina',
                'settings.expense_groups.name' => 'Nome gruppo',
                'settings.expense_groups.description' => 'Descrizione',
                'settings.expense_groups.color' => 'Colore',
                'settings.expense_groups.members' => 'Membri',
                'settings.expense_groups.members_help' => 'Solo i membri selezionati possono condividere spese e rimborsi in questo gruppo.',
                'settings.expense_groups.created' => 'Gruppo spesa creato.',
                'settings.expense_groups.updated' => 'Gruppo spesa aggiornato.',
                'settings.expense_groups.deleted' => 'Gruppo spesa eliminato.',
                'settings.expense_groups.name_required' => 'Inserisci un nome gruppo.',
                'settings.expense_groups.members_required' => 'Seleziona almeno un membro per questo gruppo spesa.',
                'settings.expense_groups.not_found' => 'Gruppo spesa non disponibile.',
                'settings.expense_groups.system_locked' => 'I gruppi di sistema non possono essere modificati qui.',
                'expense.label.group' => 'Gruppo spesa',
                'expense.label.group.general' => 'Generale',
                'expense.error.group_invalid' => 'Il gruppo spesa selezionato non e disponibile per questa household.',
                'settlement.label.group' => 'Gruppo spesa',
                'report.balance.by_member_group' => 'Per gruppo spesa del membro',
                'report.expenses.title' => 'Report spese',
                'report.expenses.lead' => 'Ripartizione per categoria, mese e membro senza conversioni FX implicite.',
                'report.expenses.by_category' => 'Per categoria',
                'report.expenses.by_month' => 'Trend mensile',
                'report.expenses.by_user' => 'Per membro',
                'report.expenses.top_spenders' => 'Top spenders',
                'report.expenses.recent' => 'Spese recenti',
                'report.expenses.chart.monthly' => 'Andamento mensile spese',
                'report.expenses.chart.categories' => 'Totali mensili per gruppo spesa',
                'report.balance.by_group' => 'Per gruppo spesa',
                'report.balance.group_unassigned' => 'Senza gruppo spesa',
                'report.balance.overall' => 'Totale complessivo',
                'report.balance.gets_back' => 'Da ricevere',
                'report.balance.owes' => 'Da pagare',
                'category.uncategorized' => 'Senza categoria',
                'category.groceries' => 'Spesa',
                'category.utilities' => 'Utenze',
                'category.rent' => 'Affitto',
                'category.internet' => 'Internet',
                'category.cleaning' => 'Pulizie',
                'category.transport' => 'Trasporti',
                'category.entertainment' => 'Svago',
                'category.misc' => 'Varie',
                'gdpr.link.privacy' => 'Privacy policy',
                'gdpr.link.cookies' => 'Cookie policy',
                'gdpr.link.manage' => 'Preferenze cookie',
                'gdpr.flash.saved' => 'Preferenze cookie aggiornate.',
                'gdpr.banner.title' => 'Privacy e scelte cookie',
                'gdpr.banner.body' => 'Usiamo cookie essenziali per login, sicurezza e funzioni household. Preferenze, analytics e marketing restano disattivati finche non scegli altrimenti.',
                'gdpr.banner.essential' => 'Solo essenziali',
                'gdpr.banner.manage' => 'Gestisci scelte',
                'gdpr.banner.accept_all' => 'Accetta tutto',
                'gdpr.modal.title' => 'Preferenze cookie',
                'gdpr.modal.body' => 'Scegli quali tecnologie opzionali possono essere abilitate su questo dispositivo. I cookie essenziali restano attivi perche necessari a sicurezza e funzioni core del prodotto.',
                'gdpr.category.necessary' => 'Strettamente necessari',
                'gdpr.category.preferences' => 'Preferenze',
                'gdpr.category.analytics' => 'Analytics',
                'gdpr.category.marketing' => 'Marketing',
                'gdpr.category.enable' => 'Abilita categoria',
                'gdpr.category.always_on' => 'Sempre attiva',
                'gdpr.category.necessary.help' => 'Necessari per autenticazione, protezione CSRF, continuita di sessione e memorizzazione del consenso.',
                'gdpr.category.preferences.help' => 'Memorizzano preferenze facoltative dell\'interfaccia, ad esempio il tema ricordato su dispositivi condivisi/pubblici.',
                'gdpr.category.analytics.help' => 'Riservata a strumenti di misurazione privacy-friendly. Nessun analytics opzionale e attivo di default.',
                'gdpr.category.marketing.help' => 'Riservata a tecnologie pubblicitarie o di retargeting. Disattivata di default.',
                'gdpr.modal.save' => 'Salva scelte',
                'gdpr.policy.version' => 'Versione policy: {version}',
                'gdpr.privacy.title' => 'Privacy policy',
                'gdpr.privacy.lead' => 'FamilyJam tratta dati di account, household e attivita per fornire budgeting condiviso, faccende, shopping e collaborazione nella household attiva.',
                'gdpr.privacy.processing.title' => 'Ambito del trattamento',
                'gdpr.privacy.processing.body' => 'Account utente, membership household, spese, faccende, shopping list, notifiche ed eventi di audit necessari a far funzionare il servizio.',
                'gdpr.privacy.cookies.title' => 'Cookie e local storage',
                'gdpr.privacy.cookies.body' => 'I cookie essenziali sono usati per sicurezza e stato di login. La memorizzazione facoltativa di preferenze resta disattivata finche non viene registrato il consenso.',
                'gdpr.privacy.bases.title' => 'Basi giuridiche',
                'gdpr.privacy.bases.contract' => 'Contratto/esecuzione del servizio per accesso account, partecipazione alla household e funzionalita collaborative.',
                'gdpr.privacy.bases.legitimate' => 'Legittimo interesse per sicurezza, prevenzione abusi, logging e resilienza operativa.',
                'gdpr.privacy.bases.consent' => 'Consenso per tecnologie facoltative di preferenza, analytics o marketing quando introdotte.',
                'gdpr.privacy.rights.title' => 'Diritti dell\'interessato',
                'gdpr.privacy.rights.body' => 'Gli utenti possono richiedere accesso, correzione o cancellazione dei dati personali secondo il quadro GDPR applicabile e la normativa locale.',
                'gdpr.privacy.rights.access' => 'Accesso e copia dei dati personali.',
                'gdpr.privacy.rights.rectification' => 'Correzione di dati inesatti o incompleti.',
                'gdpr.privacy.rights.erasure' => 'Richiesta di cancellazione quando la conservazione non e piu giustificata.',
                'gdpr.privacy.rights.portability' => 'Richiesta di dati portabili in formato strutturato dove applicabile.',
                'gdpr.privacy.rights.objection' => 'Opposizione a trattamenti facoltativi basati su consenso o legittimo interesse.',
                'gdpr.privacy.retention.title' => 'Conservazione',
                'gdpr.privacy.retention.body' => 'I dati operativi vengono conservati solo per il tempo necessario a collaborazione household, obblighi legali, gestione contestazioni e sicurezza del servizio. I record di consenso facoltativo sono versionati e mantenuti per documentare la storia delle scelte utente.',
                'gdpr.cookies.title' => 'Cookie policy',
                'gdpr.cookies.lead' => 'FamilyJam usa di default solo cookie essenziali. La memorizzazione facoltativa di preferenze, analytics e marketing resta disattivata finche il visitatore non registra una scelta esplicita.',
                'gdpr.cookies.table.name' => 'Nome',
                'gdpr.cookies.table.category' => 'Categoria',
                'gdpr.cookies.table.purpose' => 'Finalita',
                'gdpr.cookies.table.duration' => 'Durata',
                'gdpr.cookies.row.session' => 'Mantiene stato di sessione autenticata e continuita operativa dell\'applicazione.',
                'gdpr.cookies.row.consent_id' => 'Memorizza un identificatore anonimo di consenso usato per collegare la scelta del browser al log dei consensi.',
                'gdpr.cookies.row.consent_state' => 'Memorizza categorie di preferenza cookie attive e versione corrente della policy per questo browser.',
                'gdpr.cookies.row.theme' => 'Memorizza il tema ricordato solo dopo consenso preferenze o quando un utente autenticato usa esplicitamente una preferenza interfaccia salvata.',
                'gdpr.cookies.duration.session' => 'Sessione / ciclo del browser',
                'gdpr.cookies.duration.six_months' => '180 giorni',
                'gdpr.cookies.duration.browser_local' => 'Local storage del browser finche non viene cancellato o aggiornato',
                'gdpr.cookies.categories.title' => 'Categorie',
            ],
        ];

        $value = $catalog[$resolvedLocale][$key] ?? $catalog['en'][$key] ?? $key;

        foreach ($replace as $token => $replacement) {
            $value = str_replace('{' . $token . '}', (string) $replacement, $value);
        }

        return $value;
    }
}

if (! function_exists('ui_category_name')) {
    function ui_category_name(?string $code, ?string $fallbackName = null, bool $isSystem = false, ?string $locale = null): string
    {
        if ($isSystem && is_string($code) && trim($code) !== '') {
            return ui_text('category.' . strtolower(trim($code)), [], $locale);
        }

        $resolved = is_string($fallbackName) ? trim($fallbackName) : '';

        return $resolved !== '' ? $resolved : ui_text('category.uncategorized', [], $locale);
    }
}

if (! function_exists('ui_initials')) {
    function ui_initials(string $value): string
    {
        $parts = preg_split('/\s+/', trim($value)) ?: [];
        $initials = '';

        foreach (array_slice($parts, 0, 2) as $part) {
            $initials .= strtoupper(substr($part, 0, 1));
        }

        return $initials !== '' ? $initials : 'FJ';
    }
}

if (! function_exists('ui_active_class')) {
    function ui_active_class(bool $active, string $activeClass = 'is-active'): string
    {
        return $active ? $activeClass : '';
    }
}
