CREATE TABLE IF NOT EXISTS `attachments` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `household_id` BIGINT UNSIGNED NULL,
    `uploaded_by` BIGINT UNSIGNED NOT NULL,
    `entity_type` VARCHAR(64) NULL,
    `entity_id` BIGINT UNSIGNED NULL,
    `original_name` VARCHAR(255) NOT NULL,
    `stored_name` VARCHAR(255) NOT NULL,
    `mime_type` VARCHAR(100) NOT NULL,
    `file_size` BIGINT UNSIGNED NOT NULL,
    `disk` VARCHAR(32) NOT NULL DEFAULT 'local',
    `path` VARCHAR(500) NOT NULL,
    `checksum_sha256` CHAR(64) NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_attachments_disk_path` (`disk`, `path`),
    KEY `idx_attachments_household_entity` (`household_id`, `entity_type`, `entity_id`),
    KEY `idx_attachments_uploader_created` (`uploaded_by`, `created_at`),
    CONSTRAINT `fk_attachments_household` FOREIGN KEY (`household_id`) REFERENCES `households` (`id`) ON UPDATE SET NULL ON DELETE SET NULL,
    CONSTRAINT `fk_attachments_uploaded_by` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `expense_categories` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `household_id` BIGINT UNSIGNED NULL,
    `scope_household_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `code` VARCHAR(64) NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `color` VARCHAR(20) NULL,
    `icon` VARCHAR(50) NULL,
    `is_system` TINYINT(1) NOT NULL DEFAULT 0,
    `sort_order` INT UNSIGNED NOT NULL DEFAULT 0,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `created_by` BIGINT UNSIGNED NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_expense_categories_scope_code` (`scope_household_id`, `code`),
    KEY `idx_expense_categories_household_active_sort` (`household_id`, `is_active`, `sort_order`),
    CONSTRAINT `fk_expense_categories_household` FOREIGN KEY (`household_id`) REFERENCES `households` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_expense_categories_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON UPDATE SET NULL ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `recurring_rules` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `household_id` BIGINT UNSIGNED NOT NULL,
    `entity_type` VARCHAR(32) NOT NULL,
    `frequency` VARCHAR(32) NOT NULL,
    `interval_value` INT UNSIGNED NOT NULL DEFAULT 1,
    `by_weekday` JSON NULL,
    `day_of_month` TINYINT UNSIGNED NULL,
    `starts_at` DATETIME NOT NULL,
    `ends_at` DATETIME NULL,
    `next_run_at` DATETIME NULL,
    `last_run_at` DATETIME NULL,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `config_json` JSON NULL,
    `created_by` BIGINT UNSIGNED NOT NULL,
    `updated_by` BIGINT UNSIGNED NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    KEY `idx_recurring_rules_due` (`household_id`, `entity_type`, `is_active`, `next_run_at`),
    CONSTRAINT `fk_recurring_rules_household` FOREIGN KEY (`household_id`) REFERENCES `households` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_recurring_rules_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT `fk_recurring_rules_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON UPDATE SET NULL ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `expenses` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `household_id` BIGINT UNSIGNED NOT NULL,
    `recurring_rule_id` BIGINT UNSIGNED NULL,
    `category_id` BIGINT UNSIGNED NULL,
    `receipt_attachment_id` BIGINT UNSIGNED NULL,
    `title` VARCHAR(160) NOT NULL,
    `description` TEXT NULL,
    `expense_date` DATE NOT NULL,
    `currency` CHAR(3) NOT NULL,
    `total_amount` DECIMAL(12,2) NOT NULL,
    `split_method` VARCHAR(24) NOT NULL,
    `status` VARCHAR(24) NOT NULL DEFAULT 'posted',
    `created_by` BIGINT UNSIGNED NOT NULL,
    `updated_by` BIGINT UNSIGNED NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    KEY `idx_expenses_household_date` (`household_id`, `expense_date`),
    KEY `idx_expenses_household_status_date` (`household_id`, `status`, `expense_date`),
    KEY `idx_expenses_household_creator_date` (`household_id`, `created_by`, `expense_date`),
    CONSTRAINT `fk_expenses_household` FOREIGN KEY (`household_id`) REFERENCES `households` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_expenses_recurring_rule` FOREIGN KEY (`recurring_rule_id`) REFERENCES `recurring_rules` (`id`) ON UPDATE SET NULL ON DELETE SET NULL,
    CONSTRAINT `fk_expenses_category` FOREIGN KEY (`category_id`) REFERENCES `expense_categories` (`id`) ON UPDATE SET NULL ON DELETE SET NULL,
    CONSTRAINT `fk_expenses_receipt_attachment` FOREIGN KEY (`receipt_attachment_id`) REFERENCES `attachments` (`id`) ON UPDATE SET NULL ON DELETE SET NULL,
    CONSTRAINT `fk_expenses_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT `fk_expenses_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON UPDATE SET NULL ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `expense_payers` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `expense_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `amount_paid` DECIMAL(12,2) NOT NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_expense_payers_expense_user` (`expense_id`, `user_id`),
    CONSTRAINT `fk_expense_payers_expense` FOREIGN KEY (`expense_id`) REFERENCES `expenses` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_expense_payers_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `expense_splits` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `expense_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `owed_amount` DECIMAL(12,2) NOT NULL,
    `percentage` DECIMAL(5,2) NULL,
    `share_units` DECIMAL(8,2) NULL,
    `is_excluded` TINYINT(1) NOT NULL DEFAULT 0,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_expense_splits_expense_user` (`expense_id`, `user_id`),
    CONSTRAINT `fk_expense_splits_expense` FOREIGN KEY (`expense_id`) REFERENCES `expenses` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_expense_splits_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `settlements` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `household_id` BIGINT UNSIGNED NOT NULL,
    `from_user_id` BIGINT UNSIGNED NOT NULL,
    `to_user_id` BIGINT UNSIGNED NOT NULL,
    `attachment_id` BIGINT UNSIGNED NULL,
    `settlement_date` DATE NOT NULL,
    `currency` CHAR(3) NOT NULL,
    `amount` DECIMAL(12,2) NOT NULL,
    `payment_method` VARCHAR(32) NULL,
    `note` TEXT NULL,
    `created_by` BIGINT UNSIGNED NOT NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    KEY `idx_settlements_household_date` (`household_id`, `settlement_date`),
    KEY `idx_settlements_from_user_date` (`household_id`, `from_user_id`, `settlement_date`),
    KEY `idx_settlements_to_user_date` (`household_id`, `to_user_id`, `settlement_date`),
    CONSTRAINT `fk_settlements_household` FOREIGN KEY (`household_id`) REFERENCES `households` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_settlements_from_user` FOREIGN KEY (`from_user_id`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT `fk_settlements_to_user` FOREIGN KEY (`to_user_id`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT `fk_settlements_attachment` FOREIGN KEY (`attachment_id`) REFERENCES `attachments` (`id`) ON UPDATE SET NULL ON DELETE SET NULL,
    CONSTRAINT `fk_settlements_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
