CREATE TABLE IF NOT EXISTS `chores` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `household_id` BIGINT UNSIGNED NOT NULL,
    `recurring_rule_id` BIGINT UNSIGNED NULL,
    `title` VARCHAR(160) NOT NULL,
    `description` TEXT NULL,
    `assignment_mode` VARCHAR(16) NOT NULL DEFAULT 'fixed',
    `fixed_assignee_user_id` BIGINT UNSIGNED NULL,
    `rotation_anchor_user_id` BIGINT UNSIGNED NULL,
    `points` INT UNSIGNED NOT NULL DEFAULT 0,
    `estimated_minutes` INT UNSIGNED NOT NULL DEFAULT 0,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `created_by` BIGINT UNSIGNED NOT NULL,
    `updated_by` BIGINT UNSIGNED NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    KEY `idx_chores_household_active` (`household_id`, `is_active`),
    CONSTRAINT `fk_chores_household` FOREIGN KEY (`household_id`) REFERENCES `households` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_chores_recurring_rule` FOREIGN KEY (`recurring_rule_id`) REFERENCES `recurring_rules` (`id`) ON UPDATE SET NULL ON DELETE SET NULL,
    CONSTRAINT `fk_chores_fixed_assignee` FOREIGN KEY (`fixed_assignee_user_id`) REFERENCES `users` (`id`) ON UPDATE SET NULL ON DELETE SET NULL,
    CONSTRAINT `fk_chores_rotation_anchor` FOREIGN KEY (`rotation_anchor_user_id`) REFERENCES `users` (`id`) ON UPDATE SET NULL ON DELETE SET NULL,
    CONSTRAINT `fk_chores_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT `fk_chores_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON UPDATE SET NULL ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `chore_occurrences` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `household_id` BIGINT UNSIGNED NOT NULL,
    `chore_id` BIGINT UNSIGNED NOT NULL,
    `assigned_user_id` BIGINT UNSIGNED NULL,
    `due_at` DATETIME NOT NULL,
    `completed_at` DATETIME NULL,
    `completed_by` BIGINT UNSIGNED NULL,
    `skipped_at` DATETIME NULL,
    `skipped_by` BIGINT UNSIGNED NULL,
    `skip_reason` VARCHAR(255) NULL,
    `status` VARCHAR(24) NOT NULL DEFAULT 'scheduled',
    `points_awarded` INT UNSIGNED NOT NULL DEFAULT 0,
    `reminder_sent_at` DATETIME NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    KEY `idx_chore_occurrences_household_status_due` (`household_id`, `status`, `due_at`),
    KEY `idx_chore_occurrences_assignee_status_due` (`assigned_user_id`, `status`, `due_at`),
    CONSTRAINT `fk_chore_occurrences_household` FOREIGN KEY (`household_id`) REFERENCES `households` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_chore_occurrences_chore` FOREIGN KEY (`chore_id`) REFERENCES `chores` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_chore_occurrences_assigned_user` FOREIGN KEY (`assigned_user_id`) REFERENCES `users` (`id`) ON UPDATE SET NULL ON DELETE SET NULL,
    CONSTRAINT `fk_chore_occurrences_completed_by` FOREIGN KEY (`completed_by`) REFERENCES `users` (`id`) ON UPDATE SET NULL ON DELETE SET NULL,
    CONSTRAINT `fk_chore_occurrences_skipped_by` FOREIGN KEY (`skipped_by`) REFERENCES `users` (`id`) ON UPDATE SET NULL ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `shopping_lists` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `household_id` BIGINT UNSIGNED NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `is_default` TINYINT(1) NOT NULL DEFAULT 0,
    `created_by` BIGINT UNSIGNED NOT NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    KEY `idx_shopping_lists_household_default` (`household_id`, `is_default`),
    CONSTRAINT `fk_shopping_lists_household` FOREIGN KEY (`household_id`) REFERENCES `households` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_shopping_lists_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `shopping_items` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `shopping_list_id` BIGINT UNSIGNED NOT NULL,
    `household_id` BIGINT UNSIGNED NOT NULL,
    `name` VARCHAR(160) NOT NULL,
    `quantity` DECIMAL(10,2) NOT NULL DEFAULT 1.00,
    `unit` VARCHAR(32) NULL,
    `category` VARCHAR(64) NULL,
    `notes` TEXT NULL,
    `priority` VARCHAR(16) NOT NULL DEFAULT 'normal',
    `assigned_user_id` BIGINT UNSIGNED NULL,
    `position` INT UNSIGNED NOT NULL DEFAULT 0,
    `is_purchased` TINYINT(1) NOT NULL DEFAULT 0,
    `purchased_at` DATETIME NULL,
    `purchased_by` BIGINT UNSIGNED NULL,
    `converted_expense_id` BIGINT UNSIGNED NULL,
    `created_by` BIGINT UNSIGNED NOT NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    KEY `idx_shopping_items_list_purchased_position` (`shopping_list_id`, `is_purchased`, `position`),
    CONSTRAINT `fk_shopping_items_list` FOREIGN KEY (`shopping_list_id`) REFERENCES `shopping_lists` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_shopping_items_household` FOREIGN KEY (`household_id`) REFERENCES `households` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_shopping_items_assigned_user` FOREIGN KEY (`assigned_user_id`) REFERENCES `users` (`id`) ON UPDATE SET NULL ON DELETE SET NULL,
    CONSTRAINT `fk_shopping_items_purchased_by` FOREIGN KEY (`purchased_by`) REFERENCES `users` (`id`) ON UPDATE SET NULL ON DELETE SET NULL,
    CONSTRAINT `fk_shopping_items_converted_expense` FOREIGN KEY (`converted_expense_id`) REFERENCES `expenses` (`id`) ON UPDATE SET NULL ON DELETE SET NULL,
    CONSTRAINT `fk_shopping_items_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pinboard_posts` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `household_id` BIGINT UNSIGNED NOT NULL,
    `author_user_id` BIGINT UNSIGNED NOT NULL,
    `title` VARCHAR(160) NOT NULL,
    `body` LONGTEXT NOT NULL,
    `post_type` VARCHAR(32) NOT NULL DEFAULT 'note',
    `is_pinned` TINYINT(1) NOT NULL DEFAULT 0,
    `due_at` DATETIME NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    KEY `idx_pinboard_posts_household_pinned_created` (`household_id`, `is_pinned`, `created_at`),
    CONSTRAINT `fk_pinboard_posts_household` FOREIGN KEY (`household_id`) REFERENCES `households` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_pinboard_posts_author` FOREIGN KEY (`author_user_id`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pinboard_comments` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `post_id` BIGINT UNSIGNED NOT NULL,
    `author_user_id` BIGINT UNSIGNED NOT NULL,
    `body` TEXT NOT NULL,
    `created_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    KEY `idx_pinboard_comments_post_created` (`post_id`, `created_at`),
    CONSTRAINT `fk_pinboard_comments_post` FOREIGN KEY (`post_id`) REFERENCES `pinboard_posts` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_pinboard_comments_author` FOREIGN KEY (`author_user_id`) REFERENCES `users` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
